// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrackHub.Persistence.Sql.Context;

#nullable disable

namespace TrackHub.Persistence.Sql.Migrations.Migrations
{
    [DbContext(typeof(TrackHubDbContext))]
    partial class TrackHubDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TrackHub.Domain.Entities.LoginSession", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("expires_at");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("session_id");

                    b.Property<string>("user_id")
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("UserId");

                    b.HasIndex("user_id")
                        .IsUnique()
                        .HasFilter("[user_id] IS NOT NULL");

                    b.ToTable("login_sessions", null, t =>
                        {
                            t.Property("user_id")
                                .HasColumnName("user_id1");
                        });
                });

            modelBuilder.Entity("TrackHub.Domain.Entities.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)")
                        .HasColumnName("email");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("FirstPlayDate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("first_play_date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("full_name");

                    b.Property<DateTimeOffset?>("LastEntranceDate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("last_entrance_date");

                    b.Property<DateTimeOffset?>("LastPlayDate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("last_play_date");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasColumnName("photo_url");

                    b.Property<DateTimeOffset>("RegistrationDate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("registration_date");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("TrackHub.Domain.Entities.UserSongItem", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("user_id");

                    b.Property<int>("DurationPosition")
                        .HasColumnType("int")
                        .HasColumnName("position");

                    b.Property<string>("SongName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("song_name");

                    b.Property<string>("UserId1")
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("UserId", "DurationPosition");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId1");

                    b.ToTable("user_songs", (string)null);
                });

            modelBuilder.Entity("TrackHub.Domain.Entities.LoginSession", b =>
                {
                    b.HasOne("TrackHub.Domain.Entities.User", null)
                        .WithOne("LoginSession")
                        .HasForeignKey("TrackHub.Domain.Entities.LoginSession", "user_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TrackHub.Domain.Entities.UserSongItem", b =>
                {
                    b.HasOne("TrackHub.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrackHub.Domain.Entities.User", null)
                        .WithMany("UserSongItems")
                        .HasForeignKey("UserId1");
                });

            modelBuilder.Entity("TrackHub.Domain.Entities.User", b =>
                {
                    b.Navigation("LoginSession");

                    b.Navigation("UserSongItems");
                });
#pragma warning restore 612, 618
        }
    }
}
