<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.2.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TrackHub.Domain.Enums\TrackHub.Domain.Enums.csproj" />
    <ProjectReference Include="..\TrackHub.Domain\TrackHub.Domain.Entities.csproj" />
    <ProjectReference Include="..\TrackHub.Messaging\TrackHub.Messaging.csproj" />
    <ProjectReference Include="..\TrackHub.Service.Aggregation\TrackHub.Service.Aggregation.csproj" />
  </ItemGroup>

</Project>
